language: perl
perl:
 - "5.10"
 - "5.10-thr"
 - "5.12"
 - "5.12-thr"
 - "5.14"
 - "5.14-thr"
 - "5.16"
 - "5.16-thr"
 - "5.18"
 - "5.18-thr"
 - "5.20"
 - "5.20-thr"
 - "5.22"
 - "5.22-thr"
 - "5.24"
 - "5.24-thr"
 - "dev"
 - "dev-thr"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
    email:
        on_success: "change"
        on_failure: "always"
env: AUTHOR_TESTING=1 RELEASE_TESTING=1 AUTOMATED_TESTING=1 EXTENDED_TESTING=1
sudo: false
branches:
    only:
        - master
        - dev
addons:
    artifacts: true
